# Generated by Django 5.0.7 on 2024-08-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientmodel',
            name='devise',
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
