# Generated by Django 5.0.7 on 2024-08-02 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_clientmodel_devise_alter_clientmodel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmodel',
            name='location',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='user_type',
            field=models.CharField(choices=[('OU', 'Ordinary'), ('AU', 'Admin')], default='OU', max_length=2),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
