# Generated by Django 5.0.7 on 2024-08-02 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_clientmodel_location_clientmodel_user_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientmodel',
            old_name='user_type',
            new_name='rule',
        ),
    ]
