# Generated by Django 5.0.7 on 2024-08-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='famous',
            field=models.BooleanField(default=False),
        ),
    ]
