# Generated by Django 5.0.7 on 2024-08-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_category_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hot_cold',
            field=models.CharField(blank=True, choices=[('hot', 'Hot'), ('cold', 'cold')], max_length=4, null=True),
        ),
    ]
